# app
app.headless.enabled=false
app.debug.enabled=true
app.asset.dir=Assets
app.default.name=App
# threads
engine.threading.failure.level=2
engine.threading.lifetime=-1
engine.threading.multithreadEvents=false
engine.threading.event.failure.level=2
engine.threading.pre_update.failure.level=2
engine.threading.update.failure.level=2
