<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <PlatformTarget>x64</PlatformTarget>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        
        <OutputPath>bin\$(Configuration)</OutputPath>
        
        <Platforms>x64</Platforms>
        
        <Configurations>Debug;Release</Configurations>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ini-parser" Version="2.5.2" />
        <PackageReference Include="Lib.Harmony" Version="2.3.6" />
        <PackageReference Include="OpenTK.Graphics" Version="4.9.4" />
        <PackageReference Include="OpenTK.Mathematics" Version="4.9.4" />
        <PackageReference Include="OpenTK.redist.glfw" Version="3.4.0.44" />
        <PackageReference Include="SDL2-CS.NetCore" Version="2.0.8" />
        <PackageReference Include="SpaceWizards.SharpFont" Version="1.0.2" />
        <PackageReference Include="StbImageSharp" Version="2.30.15" />
    </ItemGroup>

    <!-- adding engine assets -->
    <ItemGroup>
        <Content Include="EngineData\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>

        <Content Include="freetype6.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>freetype6.dll</Link>
        </Content>

        <Content Include="SDL2.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>SDL2.dll</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Graphic\OpenGl\Buffers\" />
        <Folder Include="Graphic\OpenGl\GlObject\" />
        <Folder Include="Graphic\OpenGl\Shader\" />
        <Folder Include="Graphic\OpenGl\Texture\" />
        <Folder Include="Graphic\OpenGl\Vertex\" />
        <Folder Include="Graphic\Interface\" />
        <Folder Include="Graphic\Model\" />
        <Folder Include="Graphic\Renderer\" />
        <Folder Include="Graphic\Surface\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Natives\MirageAPI\MirageAPI.vcxproj" />
    </ItemGroup>

    <!-- adding engine binary -->

</Project>
