<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <OutDir>bin\$(Configuration)\$(TargetFramework)\bin\</OutDir>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ini-parser" Version="2.5.2" />
        <PackageReference Include="OpenTK.Graphics" Version="4.8.2" />
        <PackageReference Include="OpenTK.Mathematics" Version="4.8.2" />
        <PackageReference Include="OpenTK.redist.glfw" Version="3.4.0.44" />
        <PackageReference Include="SDL2-CS.NetCore" Version="2.0.8" />
        <PackageReference Include="SpaceWizards.SharpFont" Version="1.0.2" />
        <PackageReference Include="StbImageSharp" Version="2.30.15" />
    </ItemGroup>
    
    <!-- adding engine assets -->
    <ItemGroup>
      <Folder Include="Data\Assets\" />
    </ItemGroup>

    <!-- adding engine binary -->
    <ItemGroup>
<!--        <Content Include="Graphics\Font\freetype6.dll">-->
<!--            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>-->
<!--            <Link>freetype6.dll</Link>-->
<!--        </Content>-->

<!--        <Content Include="Graphics\Window\SDL2.dll">-->
<!--            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>-->
<!--            <Link>SDL2.dll</Link>-->
<!--        </Content>-->
    </ItemGroup>

</Project>
