# app
app.headless.enabled=false
app.debug.enabled=true
app.asset.dir=Assets
app.default.name=App
# threads
engine.threading.failure.level=Second
engine.threading.lifetime=null
engine.threading.multithreadEvents=false
engine.threading.event.failure.level=Second
engine.threading.pre_update.failure.level=Second
engine.threading.update.failure.level=Second
# dx12
engine.directx.device.adapter=HighPerformance

