<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
        <PlatformTarget>x64</PlatformTarget>

        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <RootNamespace>Engine</RootNamespace>

        <OutputPath>bin\$(Configuration)</OutputPath>

        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

        <Configurations>Debug;Release</Configurations>
        <Platforms>x64</Platforms>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SpaceWizards.SharpFont" Version="1.0.2"/>
        <PackageReference Include="StbImageSharp" Version="2.30.15"/>
    </ItemGroup>

    <!-- adding engine binary and assets -->
    <ItemGroup>
        <Content Include="freetype6.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>freetype6.dll</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="EngineData\Assets\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Natives\MirageAPI\MirageAPI.vcxproj"/>
        <ProjectReference Include="..\EngineCore\EngineCore.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="EngineData\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
