<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <!-- Project settings -->
        <RootNamespace>QuantumCore</RootNamespace>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <!-- Build configuration -->
        <Configurations>Debug;Release</Configurations>
        <PlatformTarget>x64</PlatformTarget>
        <Platforms>x64</Platforms>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
        <!-- Build path configuration -->
        <OutputPath>bin\$(Configuration)</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

        <Company>QuantumDev</Company>
        <VersionFile>EngineData\engine.core</VersionFile>
    </PropertyGroup>

    <ItemGroup>
        <!-- Libs -->
        <PackageReference Include="ini-parser" Version="2.5.2"/>
        <PackageReference Include="OpenTK.Mathematics" Version="4.9.4"/>
    </ItemGroup>

    <ItemGroup>
        <!-- Hold folders in editor -->
        <!-- Embeded Files -->
        <EmbeddedResource Include="EngineData\**\*.*">
            <LogicalName>%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
        </EmbeddedResource>
    </ItemGroup>

    <!-- Import common version management -->
    <Import Project="..\Version.targets"/>
</Project>
