<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
        <PlatformTarget>x64</PlatformTarget>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <OutputPath>bin\$(Configuration)</OutputPath>

        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

        <PublishSingleFile>false</PublishSingleFile>
        <IncludeNativeLibrariesForSelfExtract>false</IncludeNativeLibrariesForSelfExtract>

        <Configurations>Debug;Release</Configurations>
        <Platforms>x64</Platforms>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>

        <ApplicationIcon>Logo.ico</ApplicationIcon>

        <Version>0.16.3</Version>
        
        <Company>QuantumDev</Company>
        <AssemblyVersion>$(Version)</AssemblyVersion>
        <FileVersion>$(Version)</FileVersion>
        <NeutralLanguage>ru-RU</NeutralLanguage>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Launcher\Launcher.csproj"/>
        <ProjectReference Include="..\AppLib\AppLib.csproj"/>
    </ItemGroup>

    <Target Name="CopyRuntimes" AfterTargets="Build">
        <MakeDir Directories="$(OutputPath)\bin\runtimes"/>

        <ItemGroup>
            <RuntimeBinaries Include="$(OutputPath)\**\freetype6.dll"/>
        </ItemGroup>

        <Move SourceFiles="@(RuntimeBinaries)" DestinationFolder="$(OutputPath)\bin\runtimes"/>
        <RemoveDir Directories="$(OutputPath)\runtimes"/>
    </Target>

    <Target Name="MoveAppBinaries" AfterTargets="CopyRuntimes">
        <ItemGroup>
            <TempAppBinaries Include="$(OutputPath)\*.dll"/>
        </ItemGroup>

        <ItemGroup>
            <UniqueTempAppBinaries Include="@(TempAppBinaries-&gt;Distinct())"/>
        </ItemGroup>

        <Move SourceFiles="@(UniqueTempAppBinaries)" DestinationFolder="$(OutputPath)\bin"/>

        <Move SourceFiles="$(OutputPath)\bin\Launcher.dll" DestinationFolder="$(OutputPath)"/>
        <Move SourceFiles="$(OutputPath)\bin\TestApp.dll" DestinationFolder="$(OutputPath)" Condition="Exists('$(OutputPath)\bin\TestApp.dll')"/>
    </Target>

    <Target Name="MoveEngineBinaries" AfterTargets="MoveAppBinaries">
        <MakeDir Directories="$(OutputPath)\bin\Engine"/>

        <ItemGroup>
            <TempEngineBinaries Include="$(OutputPath)\**\EngineCore.dll"/>
            <TempEngineBinaries Include="$(OutputPath)\**\QuantumEngine.dll"/>
            <TempEngineBinaries Include="$(OutputPath)\**\Ijwhost.dll"/>
            <TempEngineBinaries Include="$(OutputPath)\**\HeadlessQuantumEngine.dll"/>
            <TempEngineBinaries Include="$(OutputPath)\**\MirageAPI.dll"/>
        </ItemGroup>

        <ItemGroup>
            <UniqueTempEngineBinaries Include="@(TempEngineBinaries-&gt;Distinct())"/>
        </ItemGroup>

        <Move SourceFiles="@(UniqueTempEngineBinaries)" DestinationFolder="$(OutputPath)\bin\Engine"/>
    </Target>

    <Target Name="DelTrash" AfterTargets="MoveEngineBinaries">
        <ItemGroup>
            <TrashFiles Include="$(OutputPath)\**\*.pdb"/>
        </ItemGroup>

        <Delete Files="@(TrashFiles)"/>
    </Target>

    <Target Name="PrepareForPublish" AfterTargets="Publish">
        <ItemGroup>
            <PublishFiles Include="$(OutputPath)\**\*.*"/>
        </ItemGroup>
        <Copy SourceFiles="@(PublishFiles)"
              DestinationFiles="@(PublishFiles->'$(PublishDir)\%(RecursiveDir)%(Filename)%(Extension)')"/>
    </Target>

</Project>
