<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <OutputPath>bin\$(Configuration)</OutputPath>

        <Platforms>x64</Platforms>

        <Configurations>Debug;Release</Configurations>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Launcher\Launcher.csproj" />
        <ProjectReference Include="..\AppLib\AppLib.csproj" />
    </ItemGroup>

    <Target Name="CopyRuntimes" AfterTargets="Build">
        <ItemGroup>
            <RuntimeBinaries Include="$(OutputPath)\**\SDL2.dll" />
            <RuntimeBinaries Include="$(OutputPath)\**\freetype6.dll" />
        </ItemGroup>

        <Move SourceFiles="@(RuntimeBinaries)" DestinationFolder="$(OutputPath)\bin\runtimes" />
        <RemoveDir Directories="$(OutputPath)\runtimes" />
    </Target>

    <Target Name="MoveAppBinaries" AfterTargets="CopyRuntimes">
        <ItemGroup>
            <TempAppBinaries Include="$(OutputPath)\*.dll" />
        </ItemGroup>

        <ItemGroup>
            <UniqueTempAppBinaries Include="@(TempAppBinaries-&gt;Distinct())" />
        </ItemGroup>

        <Move SourceFiles="@(UniqueTempAppBinaries)" DestinationFolder="$(OutputPath)\bin" />

        <Move SourceFiles="$(OutputPath)\bin\Launcher.dll" DestinationFolder="$(OutputPath)" />
        <Move SourceFiles="$(OutputPath)\bin\TestApp.dll" DestinationFolder="$(OutputPath)" Condition="Exists('$(OutputPath)\bin\TestApp.dll')" />
    </Target>

    <Target Name="MoveEngineBinaries" AfterTargets="MoveAppBinaries">
        <ItemGroup>
            <TempEngineBinaries Include="$(OutputPath)\**\Engine.dll" />
        </ItemGroup>

        <ItemGroup>
            <UniqueTempEngineBinaries Include="@(TempEngineBinaries-&gt;Distinct())" />
        </ItemGroup>

        <Move SourceFiles="@(UniqueTempEngineBinaries)" DestinationFolder="$(OutputPath)\bin\Engine" />
    </Target>

    <Target Name="DelTrash" AfterTargets="MoveEngineBinaries">
        <ItemGroup>
            <TrashFiles Include="$(OutputPath)\**\*.pdb" />
        </ItemGroup>

        <Delete Files="@(TrashFiles)" />
    </Target>

</Project>
