<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <!-- Project settings -->
        <RootNamespace>AppLib</RootNamespace>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <!-- Build configuration -->
        <Configurations>Debug;Release</Configurations>
        <PlatformTarget>x64</PlatformTarget>
        <Platforms>x64</Platforms>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
        <!-- Build path configuration -->
        <OutputPath>bin\$(Configuration)</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <!-- Engine -->
        <ProjectReference Include="..\QuantumEngine\QuantumEngine.csproj"/>
        <!-- Import MirageAPI for tests -->
        <ProjectReference Include="..\Natives\MirageAPI\MirageAPI.vcxproj"/>
        <!-- Other Libs -->
    </ItemGroup>

    <ItemGroup>
        <!-- Hold folders in editor -->
        <Folder Include="Assets\"/>
        <Folder Include="Assets\Embedded\"/>
    </ItemGroup>

    <ItemGroup>
        <!-- Somple Assets -->
        <Content Include="Assets\**\*.*">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <!-- Embeded Files -->
        <EmbeddedResource Include="Assets\Embedded\**\*.*">
            <LogicalName>$([System.String]::Copy('%(RecursiveDir)').Replace('\','/'))%(Filename)%(Extension)</LogicalName>
        </EmbeddedResource>
        <!-- Remove embeded assets from simple asset context-->
        <Content Remove="Assets\Embedded\**\*.*"/>

        <!-- Other Resources-->
        <!--<Content Include="Config\GameConfig.ini">-->
    </ItemGroup>

</Project>
