<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <OutputPath>bin\$(Configuration)</OutputPath>

        <Platforms>x64</Platforms>

        <Configurations>Debug;Release</Configurations>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Natives\MirageAPI\MirageAPI.vcxproj"/>
        <ProjectReference Include="..\QuantumEngine\QuantumEngine.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Assets\**\*.*"/>
        <Content Include="Assets\**\*.*">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
